# Generated by Django 5.1 on 2024-08-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_brands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbrand',
            old_name='brand',
            new_name='country',
        ),
    ]
